openapi: "3.0.0"
info:
  version: 1.0.0
  title: Fake Bank - Customer API
  license:
    name: GNU General Public License Version 3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
servers:
  - url: http://bank.olof.info/v1/customers
paths:
  /customers:
    get:
      summary: List all customers
      operationId: "getCustomers"
      responses:
        200:
          description: Customers
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Customers"
    post:
      summary: Create a customer
      operationId: "createCustomer"
      requestBody:
        content:
          "application/json":
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        201:
          description: Customer created
        500:
          description: Customer creation failed

  /customers/{email}:
    get:
      summary: Get info for a specific customer
      operationId: "getCustomer"
      parameters:
        - name: email
          in: path
          required: true
          description: The email of the customer to retrieve
          schema:
            type: string
      responses:
        200:
          description: Customer found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        404:
          description: Customer not found
components:
  schemas:
    Customer:
      required:
        - email
      properties:
        firstName:
          type: string
          maxLength: 255
        lastName:
          type: string
          maxLength: 255
        email:
          type: string
          maxLength: 100
    Customers:
      type: array
      items:
        $ref: "#/components/schemas/Customer"
