name: Fake Bank API Pipeline

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Lint using OpenAPI tools
      uses: docker://openapitools/openapi-generator-cli
      with:
        args: version
