name: Fake Bank API Pipeline

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Spectral Linting
      uses: stoplightio/spectral-action@master
      with:
        file_glob: ./*.yml
        repo_token: ${{ secrets.GITHUB_TOKEN }}
